Repository openshift/gcp-pd-csi-driver-operator, pull requests merged in 2021-03, with the labels that each got.

#16 Change the disk label name
  assets/controller.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#15 Bug 1933184: Add maxUnavailable to DaemonSets
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#17 Bug 1939865: Add CSIDriver object
  assets/csidriver.yaml
  pkg/generated/bindata.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
