Repository openshift/gcp-pd-csi-driver-operator, pull requests merged in 2025-04, with the labels that each got.

#141 CORS-3911: Add custom endpoint args from infrastructure
  pkg/operator/starter.go
  pkg/operator/starter_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#144 OCPBUGS-54336: Bump library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#145 OCPBUGS-53451: enable VolumeAttributesClass
  assets/rbac/volumeattributesclass_reader_provisioner_binding.yaml
  assets/rbac/volumeattributesclass_reader_resizer_binding.yaml
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
